version: '{branch}-{build}'
image: Visual Studio 2015

environment:
 matrix:
  - QTDIR: C:\Qt\5.9\msvc2015
    CMAKE_GENERATOR: "NMake Makefiles"
  - QTDIR: C:\Qt\5.9\msvc2015_64
    CMAKE_GENERATOR: "NMake Makefiles"
  - QTDIR: C:\Qt\5.10\msvc2015
    CMAKE_GENERATOR: "NMake Makefiles"
  - QTDIR: C:\Qt\5.10\msvc2015_64
    CMAKE_GENERATOR: "NMake Makefiles"
  - QTDIR: C:\Qt\5.11\msvc2015
    CMAKE_GENERATOR: "NMake Makefiles"
  - QTDIR: C:\Qt\5.11\msvc2015_64
    CMAKE_GENERATOR: "NMake Makefiles"
  - QTDIR: C:\Qt\5.12\msvc2015_64
    CMAKE_GENERATOR: "NMake Makefiles"
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    QTDIR: C:\Qt\5.12\msvc2017
    CMAKE_GENERATOR: "NMake Makefiles"
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    QTDIR: C:\Qt\5.12\msvc2017_64
    CMAKE_GENERATOR: "NMake Makefiles"

install:
 - set PATH=%QTDIR%\bin;%MINGWDIR%\bin;%PATH%
 - qmake -v
 - if %QTDIR:_64=%==%QTDIR% ( set OPENSSL_ROOT_DIR=C:\OpenSSL-Win32 ) else set OPENSSL_ROOT_DIR=C:\OpenSSL-Win64
 - if %QTDIR:msvc=%==%QTDIR% g++ --version
 - if %QTDIR:msvc=%==%QTDIR% set make=mingw32-make.exe
 - if %QTDIR:msvc=%==%QTDIR% set PATH=%QTDIR%\bin;%MINGWDIR%\bin;C:\Program Files (x86)\CMake\bin
 - if %QTDIR:msvc=%==%QTDIR% %make% --version
 - if not %QTDIR:msvc2015=%==%QTDIR% (
       if not %QTDIR:_64=%==%QTDIR% (
           call "%ProgramFiles%\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 &&
           call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
       ) else call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
   )
 - if not %QTDIR:msvc2017=%==%QTDIR% (
       if not %QTDIR:_64=%==%QTDIR% (
           call "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
       ) else call "%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
   )
 - if not %QTDIR:msvc=%==%QTDIR% set make=nmake.exe
 - if not %QTDIR:msvc=%==%QTDIR% %make% /? > nul

build_script:
 - cd %APPVEYOR_BUILD_FOLDER%
 - cmake . -G "%CMAKE_GENERATOR%" -DQTERM_ENABLE_SCRIPT_DEBUGGER=On -DCMAKE_BUILD_TYPE=Release -DQT5=Yes
 - '%make% VERBOSE=1'
 - if not %QTDIR:msvc=%==%QTDIR% %make% package

artifacts:
 - path: QTerm*-win64.exe
   name: Win64Installer
 - path: QTerm*-win32.exe
   name: Win32Installer

deploy:
  - provider: GitHub
    artifact: Win64Installer
    auth_token:
      secure: wc0cFfZSLHWbW3W8FKqgVPHQfF0bV1l54wkpLcpsq4EuBliQdwfV+4JLnWuHBdr4
    on:
      appveyor_repo_tag: true
      QTDIR: C:\Qt\5.12\msvc2017_64
  - provider: GitHub
    artifact: Win32Installer
    auth_token:
      secure: wc0cFfZSLHWbW3W8FKqgVPHQfF0bV1l54wkpLcpsq4EuBliQdwfV+4JLnWuHBdr4
    on:
      appveyor_repo_tag: true
      QTDIR: C:\Qt\5.12\msvc2017
